### ISSUE TITLE
vault-broker Should Renew Bound Authentication Tokens

### ISSUE THREAD

**Issue by 2mOlaf** [cloudfoundry-community/vault-broker#8]
As a user/developer, I expect the Vault service broker to handle token authorization TTLs within my service binding for me.

Vault broker currently does not keep up with token authorizations except to revoke them upon unbinding. However, the broker nor the end user necessarily know what the policy TTL is for a given mount point. Presently, an expired authorization results in a access-denied failure from the bound app.

Success: Vault broker captures authorization details - specifically TTL - and auto-renews the token before expiration (e.g. n/2).

**Comment by jhunt** [comment]
Agreed.  Since we get the `lease_duration` from Vault when we issue the token creation, this is doable with a simple scheduler goroutine to issue the renewal request to Vault.  If renewal fails (for whatever reason) the app is still going to have to handle it, but it shouldn't be a matter of normal operation.

:+1:

**Comment by meizhou0** [comment]
Should the scheduler goroutine of renewal be included to service broker functions,  or should it be part of vault service itself?

**Comment by jhunt** [comment]
The Vault service itself is just Vault, which doesn't support auto-renewal to my knowledge.  In fact, handling this on behalf of the application at all is kind of antithetical to the way Vault wants consumers to manage their tokens -- they expire for a reason.

If the applications aren't going to manage the renewal themselves, the service broker is the only logical place for it given the current architecture.

**Comment by jhunt** [comment]
@gradinDotCom wanna take 0630ccd for a whirl and see if the renewal logic works for you?

**Comment by jhunt** [comment]
Actually, @gradinDotCom try latest master, b1ee7a3 -- it handles unbinds gracefully.

**Comment by 2mOlaf** [comment]
We finally put this into play today. I was comparing how you did it versus Hashicorp's broker and it looks pretty simple. I'll let you know if we find any problems. Thanks!

**Comment by jhunt** [comment]
Considering this resolved since I haven't heard otherwise.  Cheers!
